# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=10)),
                ('controller', models.CharField(max_length=300)),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(max_length=50)),
                ('lastmodifieddate', models.DateTimeField()),
                ('lastmodifiedby', models.CharField(max_length=50)),
            ],
        ),
    ]
