# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
