# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160702_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='desc',
            new_name='description',
        ),
    ]
