# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_barcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='barcode',
        ),
    ]
