# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
                ('controller', models.CharField(max_length=300)),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(max_length=50)),
                ('lastmodifieddate', models.DateTimeField()),
                ('lastmodifiedby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(max_length=50)),
                ('lastmodifieddate', models.DateTimeField()),
                ('lastmodifiedby', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('createddate', models.DateTimeField()),
                ('createdby', models.CharField(max_length=50)),
                ('lastmodifieddate', models.DateTimeField()),
                ('lastmodifiedby', models.CharField(max_length=50)),
                ('regionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Region')),
            ],
        ),
    ]
