# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshift',
            old_name='regionid',
            new_name='region',
        ),
    ]
