# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20160712_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 0, 34, 39, 66432)),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='lastmodifieddate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 0, 34, 39, 66432)),
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='workshift',
            table='workshift',
        ),
    ]
