# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20160718_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='createddate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 0, 35, 38, 447643)),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='lastmodifieddate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 0, 35, 38, 447643)),
        ),
        migrations.AlterModelTable(
            name='region',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workshift',
            table=None,
        ),
    ]
